language: node_js
node_js:
    - "4.6"

branches:
    only:
        - master
        - dev

install:
    - npm install

cache:
    directories:
        - node_modules

addons:
  code_climate:
    repo_token: 7392236f589ea30062edd08ff657ea41951df4fa74143c9a892b81ede2f50a04

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm test
    - npm run coverage

after_script:
    - codeclimate < coverage/lcov.info